### ISSUE TITLE
typo in ansible/install_docker.yaml

### ISSUE THREAD

**Issue by mattbaumann** [studentenportal/deploy-new#23]
```yaml
    - name: Template demon config
      copy:
        src: "files/docker-config/deamon.json"
        dest: "/etc/docker/deamon.json"
```
Misspelling in word _deamon_ and should be _daemon_. Plus update task name to same lettering.
